[package]
name = "rusty_scarab"
version = "0.1.0"
edition = "2021"

[dependencies]


[dependencies.tokio]
version = "1.39.2"
features = ["full"]
[dependencies.tokio-macros]
version = "2.4.0"

[dependencies.backend]
path = "backend"
[dependencies.frontend]
path = "frontend"
